-- 판매 날짜, 상품 ID, 유저ID, 판매량
-- 2022년 3월
-- offline_sale 테이블의 user_ID는 null로 표시
-- 판매일 기준 오름차순 -> 상품 ID 오름차순 -> 유저ID 오름차순

(SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = DATE_FORMAT("2022-03-00", "%Y-%m"))
UNION ALL
(SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = DATE_FORMAT("2022-03-00", "%Y-%m"))
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID