-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR 
FROM FIRST_HALF JOIN ICECREAM_INFO
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE TOTAL_ORDER > 3000 
AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;

-- 맛 출력
-- 주문량 > 3000
-- 주성분 = 과일
-- 총 주문량 큰 순서대로 조회