-- V 회원ID(USER, BOARD), 닉네임(USER), 총거래금액 조회(BOARD -> 집계) 조회
-- V 완료된 중고거래
-- V 총거래금액 70 이상
-- V 총거래금액 오름차순

SELECT WRITER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_USER AS U
ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
