-- 가격대별(만원단위), 상품개수 출력
-- 각 컬럼명 PRICE_GROUP, PRODUCTS
-- 가격대 -> 버림해서 표시
-- 가격대 오름차순

SELECT PRICE AS PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCTS
FROM 

(SELECT PRODUCT_ID, (TRUNCATE(PRICE * 0.0001, 0) * 10000 ) AS PRICE
FROM PRODUCT) AS PRODUCT

GROUP BY PRICE
ORDER BY PRICE_GROUP