-- 창고ID, 이름, 주소, 냉동시설여부 조회
-- 경기도에 위치
-- 냉동시설여부 NULL -> 'N'으로 출력
-- 창고ID 오름차순

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, 
CASE 
    WHEN FREEZER_YN IS NULL THEN 'N' 
    WHEN FREEZER_YN IS NOT NULL THEN FREEZER_YN 
END AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE "%경기%"
ORDER BY WAREHOUSE_ID